### ISSUE TITLE
Support for Deuteranopia in Markdown Preview

### ISSUE THREAD

**Issue by ddulic** [jarodise/Dracula-for-Obsidian.md#3]
I can show an example, but now sure helpful it will be.

<img width="1418" alt="Screenshot 2020-07-17 at 11 53 53" src="https://user-images.githubusercontent.com/10076428/87779136-39a95d00-c824-11ea-995a-1cd5440b6cbe.png">

There is an issue viewing the Markdown Preview inline code for people with red-green color blindness.

The following code block makes it viewable in the editor

```css
/* in-line block for editor */
.cm-s-obsidian span.cm-inline-code,
.cm-s-obsidian span.cm-inline-code.cm-hmd-indented-code,
.cm-s-obsidian span.cm-inline-code:not(.cm-formatting):not(.cm-hmd-indented-code)
{
  background-color: var(--pre-code-bg);
  color: var(--inline-code) !important;
  bottom: 0px !important;
}
```

But I am not sure how I can replicate it in the Preview mode.

Thanks!
